version: '3.8'

services:
  minihttpjob-admin:
    build:
      context: .
      dockerfile: Dockerfile.Admin
    ports:
      - "5000:8080"
      - "5001:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/MiniHttpJob.db
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - minihttpjob-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  minihttpjob-worker:
    build:
      context: .
      dockerfile: Dockerfile.Worker
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/MiniHttpJobWorker.db
      - Worker__ProcessingIntervalSeconds=10
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - minihttpjob-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - minihttpjob-admin

networks:
  minihttpjob-network:
    driver: bridge

volumes:
  minihttpjob-data:
  minihttpjob-logs: